server:
  port: 20014
spring:
  application:
    name: config-client
name: luush
age: 18
message: this is a test config file
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:28888/eureka/
